#pragma once

// Community-only UI strings live in the executable, not the original ttpres.dll.
#define IDS_FULLSCREEN_MONITOR 4091
#define IDS_FULLSCREEN_DISPLAY 4093
#define IDS_FULLSCREEN_PRIMARY 4094
#define IDS_FULLSCREEN_ALBUM 4095
#define IDS_FULLSCREEN_ALBUM_GROUP 4096
#define IDS_FULLSCREEN_ALBUM_FALLBACK 4097
#define IDS_FULLSCREEN_ALBUM_BROWSE 4098
#define IDS_FULLSCREEN_ALBUM_CLEAR 4099
#define IDS_FULLSCREEN_ALBUM_TRANSPARENCY 4100
#define IDS_FULLSCREEN_ALBUM_PICKER 4101
#define IDS_FULLSCREEN_ALBUM_FILTER 4102
#define IDS_FULLSCREEN_LYRIC_DRAG 4103
#define IDS_DESKTOP_LYRIC_ZOOM_IN 4104
#define IDS_DESKTOP_LYRIC_ZOOM_OUT 4105

#define IDC_FULLSCREEN_ALBUM_PATH 0xe920
#define IDC_FULLSCREEN_ALBUM_BROWSE 0xe921
#define IDC_FULLSCREEN_ALBUM_CLEAR 0xe922
#define IDC_FULLSCREEN_ALBUM_TRANSPARENCY 0xe923
#define IDC_FULLSCREEN_ALBUM_PERCENT 0xe924
#define IDC_FULLSCREEN_LYRIC_DRAG 0xe925
#define IDC_DESKTOP_LYRIC_ZOOM_IN 0xe926
#define IDC_DESKTOP_LYRIC_ZOOM_OUT 0xe927
