string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef fixture_id)
set(fixture "${TEST_ROOT}/stage-settings-${fixture_id}")
set(SOURCE_DIRECTORY "${fixture}/source")
set(DESTINATION "${fixture}/destination")
file(MAKE_DIRECTORY "${SOURCE_DIRECTORY}" "${DESTINATION}")
set(stage "${CMAKE_CURRENT_LIST_DIR}/stage_settings.cmake")
include("${stage}")
if(EXISTS "${DESTINATION}/TTPlayerRebuild.xml")
  message(FATAL_ERROR "Missing source created a config")
endif()
file(WRITE "${SOURCE_DIRECTORY}/TTPlayer.xml" "original source")
file(WRITE "${SOURCE_DIRECTORY}/TTPlayerRebuild.xml" "new source")
file(WRITE "${DESTINATION}/TTPlayer.xml" "existing user settings")
include("${stage}")
file(READ "${DESTINATION}/TTPlayerRebuild.xml" imported)
file(READ "${DESTINATION}/TTPlayer.xml" original)
if(NOT imported STREQUAL "existing user settings" OR NOT original STREQUAL imported)
  message(FATAL_ERROR "Existing user settings were not imported non-destructively")
endif()
file(WRITE "${DESTINATION}/TTPlayerRebuild.xml" "edited user settings")
include("${stage}")
file(READ "${DESTINATION}/TTPlayerRebuild.xml" preserved)
if(NOT preserved STREQUAL "edited user settings")
  message(FATAL_ERROR "Incremental staging overwrote user settings")
endif()
set(DESTINATION "${fixture}/fresh")
include("${stage}")
file(READ "${DESTINATION}/TTPlayerRebuild.xml" imported)
if(NOT imported STREQUAL "new source")
  message(FATAL_ERROR "Fresh output did not prefer the new source config")
endif()
set(SOURCE_DIRECTORY "${fixture}/legacy-source")
set(DESTINATION "${fixture}/legacy-output")
file(MAKE_DIRECTORY "${SOURCE_DIRECTORY}")
file(WRITE "${SOURCE_DIRECTORY}/TTPlayer.xml" "legacy only")
include("${stage}")
file(READ "${DESTINATION}/TTPlayerRebuild.xml" imported)
if(NOT imported STREQUAL "legacy only" OR EXISTS "${DESTINATION}/TTPlayer.xml")
  message(FATAL_ERROR "Legacy source was not staged under the new filename")
endif()
message(STATUS "Settings staging tests passed: ${fixture}")
